name = input("Enter your name: ")
# result = name.upper()
# result = name.startswith("A")
# result = name.replace("a", "@")
# result = name.isalpha()
# result = name.isdigit()
# result = name.split(" ")
result = name.replace("-", "f")
print(result)